defmodule Krebs.SchemaGen do
  @moduledoc """
  Generates Rekto schema source code from field specifications.
  Stateless — no GUI dependency. Used by both the MCP tools and the neoplasm GUI.
  """

  @type field_spec ::
          {String.t(), String.t(), non_neg_integer(), non_neg_integer(), String.t()}

  # --------------------------------------------------------------------------
  # Validation
  # --------------------------------------------------------------------------

  @spec validate(String.t(), [field_spec()]) :: [String.t()]
  def validate(module_name, fields) do
    []
    |> validate_module_name(module_name)
    |> validate_fields(fields)
    |> Enum.reverse()
  end

  defp validate_module_name(errors, name) do
    trimmed = String.trim(name)

    cond do
      trimmed == "" ->
        ["Module name is required" | errors]

      not Regex.match?(~r/^[A-Z][A-Za-z0-9]*(\.[A-Z][A-Za-z0-9]*)*$/, trimmed) ->
        ["Invalid module name: #{trimmed}" | errors]

      true ->
        errors
    end
  end

  defp validate_fields(errors, []) do
    ["At least one field is required" | errors]
  end

  defp validate_fields(errors, fields) do
    errors
    |> validate_field_names(fields)
    |> validate_no_duplicates(fields)
    |> validate_offsets(fields)
  end

  defp validate_field_names(errors, fields) do
    reserved = ~w(__meta__ __struct__ __garbage__)

    Enum.reduce(fields, errors, fn {name, _type, _offset, _size, _constraints}, acc ->
      trimmed = String.trim(name)

      cond do
        trimmed == "" ->
          ["Field name is empty" | acc]

        not Regex.match?(~r/^[a-z_][a-zA-Z0-9_]*$/, trimmed) ->
          ["Invalid field name: #{trimmed}" | acc]

        trimmed in reserved ->
          ["Reserved field name: #{trimmed}" | acc]

        true ->
          acc
      end
    end)
  end

  defp validate_no_duplicates(errors, fields) do
    names = Enum.map(fields, fn {name, _, _, _, _} -> String.trim(name) end)

    case names -- Enum.uniq(names) do
      [] -> errors
      dupes -> ["Duplicate field names: #{Enum.join(Enum.uniq(dupes), ", ")}" | errors]
    end
  end

  defp validate_offsets(errors, fields) do
    sorted = Enum.sort_by(fields, fn {_, _, offset, _, _} -> offset end)

    Enum.reduce(sorted, {errors, nil}, fn {name, _type, offset, size, _constraints},
                                          {acc, prev} ->
      acc =
        case prev do
          {prev_name, prev_end} when offset < prev_end ->
            ["Fields overlap: #{prev_name} and #{name} at offset 0x#{Integer.to_string(offset, 16)}" | acc]

          _ ->
            acc
        end

      {acc, {name, offset + size}}
    end)
    |> elem(0)
  end

  # --------------------------------------------------------------------------
  # Code generation
  # --------------------------------------------------------------------------

  @spec generate(String.t(), non_neg_integer(), [field_spec()]) ::
          {:ok, String.t()} | {:error, String.t()}
  def generate(module_name, base_addr, fields) do
    errors = validate(module_name, fields)

    if errors != [] do
      {:error, Enum.join(errors, "\n")}
    else
      sorted = Enum.sort_by(fields, fn {_, _, offset, _, _} -> offset end)
      code = do_generate(module_name, base_addr, sorted)
      {:ok, code}
    end
  end

  defp do_generate(module_name, base_addr, fields) do
    timestamp = DateTime.utc_now() |> DateTime.to_iso8601()
    base_hex = "0x" <> String.upcase(Integer.to_string(base_addr, 16))

    field_lines =
      fields
      |> emit_fields()
      |> Enum.map(&("    " <> &1))
      |> Enum.join("\n")

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      Generated by Krebs.SchemaGen from memory at #{base_hex}
      #{timestamp}
      \"\"\"

      use Rekto.Schema

      schema do
    #{field_lines}
      end
    end
    """
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp emit_fields(fields) do
    {lines, _} =
      Enum.reduce(fields, {[], 0}, fn {name, type_str, offset, size, constraints},
                                      {acc, expected_offset} ->
        opts = build_opts(offset, expected_offset, size, constraints)
        line = build_field_line(name, type_str, opts)
        {[line | acc], offset + size}
      end)

    Enum.reverse(lines)
  end

  defp build_opts(offset, expected_offset, _size, constraints) do
    opts = []

    # Emit offset when there's a gap (field doesn't start where previous ended)
    opts =
      if offset != expected_offset do
        ["offset: 0x" <> String.upcase(Integer.to_string(offset, 16)) | opts]
      else
        opts
      end

    # Emit constraints if non-empty
    opts =
      case String.trim(constraints) do
        "" -> opts
        c -> ["constraints: [#{c}]" | opts]
      end

    Enum.reverse(opts)
  end

  defp build_field_line(name, type_str, opts) do
    type_expr = type_to_elixir(type_str)

    case opts do
      [] -> "field :#{name}, #{type_expr}"
      _ -> "field :#{name}, #{type_expr}, #{Enum.join(opts, ", ")}"
    end
  end

  @doc false
  def type_to_elixir(type_str) do
    case type_str do
      # Primitives → atoms
      t when t in ~w(bool byte u8 i8 u16 i16 u32 i32 u64 i64 f32 f64 word) ->
        ":" <> t

      # Special types
      "vtable" -> ":vtable"
      "void_pointer" -> ":void_pointer"
      "this_pointer" -> ":this_pointer"

      # String buffer: "[string_buffer; N]"
      "[string_buffer; " <> rest ->
        n = String.trim_trailing(rest, "]")
        "{:string_buffer, #{n}}"

      # Array: "[elem; count]" → {elem_atom, count}
      "[" <> rest when byte_size(rest) > 0 ->
        trimmed = String.trim_trailing(rest, "]")

        case String.split(trimmed, ";", parts: 2) do
          [elem, count] ->
            elem_type = type_to_elixir(String.trim(elem))
            "{#{elem_type}, #{String.trim(count)}}"

          _ ->
            type_str
        end

      # Schema module reference
      other -> other
    end
  end

  # --------------------------------------------------------------------------
  # Load (compile into VM)
  # --------------------------------------------------------------------------

  @spec load(String.t()) :: {:ok, String.t()} | {:error, String.t()}
  def load(code) do
    case Code.compile_string(code) do
      [{module, _binary} | _] ->
        if function_exported?(Rekto.SchemaRegistry, :register, 1) do
          Rekto.SchemaRegistry.register(module)
        end

        {:ok, "Loaded #{inspect(module)}"}

      [] ->
        {:error, "No module compiled from source"}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  # --------------------------------------------------------------------------
  # Save to disk
  # --------------------------------------------------------------------------

  @spec save(String.t(), String.t()) :: :ok | {:error, String.t()}
  def save(code, path) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, code)
    :ok
  rescue
    e -> {:error, Exception.message(e)}
  end
end
